mini-sora/minisora

README.md

add DDPM and Score-Based difffusion model papers

[Doc] Adding DDPM and Score-Based difffusion model papers

---

README.md

Add basic video diffusion model (VDM) and MCVD.

[Doc] Add VDM and MCVD papers

---

README.md

1. adding `DDIM` paper to section `Diffusion Models`
2. adding **short model names** for papers in section `Diffusion Models`

[Doc] Update README.md  in section `Diffusion Models`

---

README.md

1. 添加网址Sora: https://openai.com/sora
2. 捋顺社区介绍

[]Doc] Update README.md 添加Sora网址和修改社区介绍

---

README.md

Update README with other curated resources on video diffusion and generation

Update README with other curated resources

---

README.md
README_EN.md

Add the [Würstchen](https://openreview.net/forum?id=gU58d5QeGv) architecture for Diffusion model.
Updated existing resources, added Datawhale's Feishu documents. Also, moved up the order of the two review projects with published papers to facilitate comparison when writing our own reviews.
All modifications have been synchronized to both the Chinese and English READMEs.

Update README with new diffusion model architecture and existing resources

---

README_EN.md

adding VideoPoet and MAGVIT papers in Video Generation to README_EN.md

adding VideoPoet and MAGVIT papers in Video Generation to README_EN.md

---

README.md

adding MAGVIT paper in Video Generation and adding bold fonts with ViViT

adding MAGVIT paper in Video Generation and adding bold fonts with ViViT

---

README_EN.md

Add openDiT to  README_EN.md

---

README.md

add openDiT

---

README_EN.md

add 
- [**OpenDiT**: An Easy, Fast and Memory-Efficent System for DiT Training and Inference](https://github.com/NUS-HPC-AI-Lab/OpenDiT)

add Hot News with OpenDiT to README_EN.md

---

README.md

add 最近更新 with OpenDiT to README.md

add 最近更新 with OpenDiT to README.md

---

README.md

- [Asking for presenter of DiT Paper](https://github.com/orgs/mini-sora/discussions/39)
- [Asking for presenter of Latte Paper](https://github.com/orgs/mini-sora/discussions/38)

Update README.md  论文共读发表者募集

---

README_EN.md

Update README_EN.md with Recruitment of presenter

Update README_EN.md with Recruitment of presenter

---

README.md

Sora: A Review on Background, Technology, Limitations, and Opportunities of Large Vision Models

Update README.md add a review

---

README.md

add short names(Stable Cascade, W.A.L.T ) for papers

add short names(Stable Cascade, W.A.L.T ) for papers in README.md

---

README.md

Stable Cascade: Wuerstchen: An Efficient Architecture for Large-Scale Text-to-Image Diffusion Models

Update Stable Cascade paper name in README.md

---

README_EN.md

Update Stable Cascade paper name

Update Stable Cascade paper name in README_EN.md

---

README_EN.md

Update WALT paper name and project in README_EN.md

---

README.md
README_EN.md

This pull request adds information about the SimDA paper and project to the README file. SimDA is a parameter-efficient video diffusion model for text-guided video generation and editing.
- Added a section in the README with links to the SimDA paper, GitHub repository, and project website.
- The addition of SimDA to our README will provide valuable resources for users interested in efficient video generation.

add video generation paper SimDA

---

README.md
README_EN.md

Revert "Revert "add video generation paper SimDA""

---

README.md

[Doc] Update 圆桌讨论 in README.md
下撤二维码, 
添加微信视频号
PPT链接

[Doc] Update 圆桌讨论 in README.md

---

notes/README.md

[**数据有关笔记**](./dataset_note.md)
[**latte论文精读翻译.pdf**](./latte%E8%AE%BA%E6%96%87%E7%B2%BE%E8%AF%BB%E7%BF%BB%E8%AF%91.pdf)

[ Doc ] Update Note folder README.md file

---

README.md

[Doc] add latte论文精读翻译.pdf to README.md

---

README.md

Update README.md with star history

Update README.md with star history

---

notes/Latte.md

modify Latte.md format

---

README.md

Update README.md : removing TG

---

README_EN.md

replace the words in buckets
1. Intensive Reading of Translated Latte Paper
2. Notes of Latte Paper in Chinese

[docs]: optimize words usage of two sources in README_EN.md

---

codes/WALT/README.md

Add WALT codes later after the codes of it are released

Add WALT codes later after the codes of it are released

---

codes/README.md

add the release dates of code forked from original works

add the release dates of code forked from original works in README.md of Codes

---

README.md
README_EN.md

This pull request fixes the spelling mistakes of OpenDiT title in README.md and README_EN.md. The word `efficent` should be replaced with `efficient`.
- Replace the word `efficent` to `efficient`.
- See https://github.com/NUS-HPC-AI-Lab/OpenDiT/issues/68.
- There were spelling errors in the OpenDiT project, and I helped them fix them and get them approved. See https://github.com/NUS-HPC-AI-Lab/OpenDiT and https://github.com/NUS-HPC-AI-Lab/OpenDiT/pull/67.

[docs]: fix spelling mistakes of OpenDiT title in README.md and README_EN.md

---

README.md
README_EN.md

`| 8) Diffusion Models in Vision: A Survey| [**TPAMI 2023 Paper**](https://arxiv.org/abs/2011.13456), [Github](https://github.com/CroitoruAlin/Diffusion-Models-in-Vision-A-Survey)|`

[Docs] add paper `Diffusion Models in Vision: A Survey`

---

README.md
README_EN.md

This pull request adds and updates conference name and year to each paper in README.md and README_EN.md
- Add and update conference name and year to each paper in README.md and README_EN.md
- See https://github.com/mini-sora/minisora/issues/101
- None

[docs]: add and update conference name and year to each paper in README.md and README_EN.md

---

README.md
README_EN.md

101 add conferencename year to each paper in the colomn of links or 链接

101 add conferencename year to each paper in the colomn of links or 链接

---

README.md

1. GPU-Green: 最好对GPU内存大小和GPU数量要求较低，比如8卡A100，4KA6000，单卡Rtx4090之类的算力可以训练和推理
2. 对训练时长友好：不需要训练太久即可有较好的效果
3. 生成视频长度和分辨率不追求过高， 如3-10s，480p都是可接受的
候选复现论文主要有以下三篇，来作为后续Sora复现的Baseline，社区已经(02/29)将OpenDiT和SiT代码Fork到codes文件夹下，期待贡献者提交PR，将Baseline代码迁移到Sora复现工作上来。
- DiT with OpenDiT
- SiT
- W.A.L.T(还未release)
**提交PR或者Issue后**，可以申请加入MiniSora贡献者社群并申请加入 Sora 有关论文复现小组！

[Docs] Adding requirements and goals for reproducing Sora, and adjusting the entry method for the replication group

---

README.md

Ref https://github.com/mini-sora/minisora/pull/111

[Docs] Adding requirements and goals for reproducing Sora, and adjusting the entry method for the replication group in README.md

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
README.md

Add pull request and issue templates to the repository
- Added a pull request template
- Added issue templates
Mention any specific points you would like reviewers to focus on, such as complex code changes or possible alternative approaches considered.
- Other ...
Link the GitHub issues that are addressed or related to this pull request.
- Closes #109
Include any other relevant …

[doc] add pr and issue templates

---

README.md

**This PR adds Add SVD,ADD papers and Audio Related Resource with Stable Audio**
- **Added a section** [**Audio Related Resource**] in the README with links to the SimDA paper, GitHub repository, and project website.
- **Added two papers** in the README with links to GitHub repository.
- **Updated** `论文复现小组` parts
- **Change** `Task` to `Link` in **现有高质量资料 7)**
Mention any specific points you would like reviewers to focus on, such as complex code changes or possible alternative approaches considered.
- Please review the added …

[Docs] add SVD,ADD papers and Audio Related Resource with Stable Audio

---

README.md

Please summarize the changes introduced by this pull request concisely.
Add Consistency Section with two Papers
List out the key modifications made in this pull request. Be sure to include any new files, updated functions, or significant refactoring.
| <h3>一致性/Consistency </h3> | |
| :------------- | :------------- |
| **论文**  | **链接** |
| 1) Layered Neural Atlases for Consistent Video Editing | [**TOG 21 Paper**](https://arxiv.org/pdf/2109.11418.pdf), [Github](https://github.com/ykasten/layered-neural-atlases), …

[Docs] Add Consistency Section with two Papers

---

README.md

Please summarize the changes introduced by this pull request concisely.
**This PR adds CoDeF paper in `Audio Related Resource`**
List out the key modifications made in this pull request. Be sure to include any new files, updated functions, or significant refactoring.
| 2) **CoDeF**: Content Deformation Fields for Temporally Consistent Video Processing | [Paper](https://arxiv.org/pdf/2308.07926.pdf), [Github](https://github.com/qiuyu96/CoDeF), [Project](https://qiuyu96.github.io/CoDeF/) |
Mention any specific points you would …

[Docs] add CoDeF paper in `Audio Related Resource`

---

README.md

Update README.md Move CoDeF to Consistency section
Please summarize the changes introduced by this pull request concisely.
**Update README.md Move CoDeF to Consistency section**
List out the key modifications made in this pull request. Be sure to include any new files, updated functions, or significant refactoring.
- Added / Updated / Deleted / Fixed / Refactored ...
Example:
> - Added a section in the README with links to the SimDA paper, GitHub repository, and project website.
> - Ensured that the links are functional and the …

[Docs] Update README.md Move CoDeF to Consistency section

---

README.md
README_EN.md

Add reference material(Open-Sora-Plan(PKU-YuanGroup) Repo) in the README. They have done some work about the reproduce of Sora, such as using `Video-VQVAE (VideoGPT) + DiT` as their base pipeline. Codes of their work are also open-sourced. I think it's a good reference for our community!
> This PR adds new work which is opened tody in the "相关工作" section of README, with a link to the `Open-Sora-Plan` github repo. They have done some work about the reproduce of Sora, such as using `Video-VQVAE (VideoGPT) + DiT` as their base …

add reference material: Open-Sora-Plan(PKU-YuanGroup) in README

---

README.md

Add Dataset Section and Panda-70M dataset
- Add Dataset Section and Panda-70M dataset
- Remove Chinese in Section Names
Mention any specific points you would like reviewers to focus on, such as complex code changes or possible alternative approaches considered.
Link the GitHub issues that are addressed or related to this pull request.
- Closes #issue-number (if there's an associated …

Add Dataset Section and Panda-70M dataset

---

README.md

Add Notes : A Survey on Generative Diffusion Model 生成扩散模型综述 - 知乎
Add Notes : A Survey on Generative Diffusion Model 生成扩散模型综述 - 知乎

Add Notes : A Survey on Generative Diffusion Model 生成扩散模型综述 - 知乎

---

README.md
README_EN.md

-Added paper link for Dataset Panda-70M
-FIx inconsistency between chinese readme and english readme (based on chinese readme)
-Added UFC-101 dataset in chinese readme and english readme

Added UFC 101 dataset

---

.github/ISSUE_TEMPLATE/custom.md

This PR updates the issue template. It might be more suitable for minisora's needs.
- Added a title template with tag formats.
- Updated issue formats better for our community.
Mention any specific points you would like reviewers to focus on, such as complex code changes or possible alternative approaches considered.
Link the GitHub issues that are addressed or related to this pull …

[Update] - update title and issue formats of the issue template

---

codes/Notes_Sora.md

[Create] Notes_Sora.md

---

codes/README.md

Update README.md in ./codes/README.md

Update README.md in ./codes/README.md

---

README.md

This PR updates information about replication group in README.md
> - Updated replication goal
> - Added a replication group link to https://github.com/mini-sora/minisora/tree/main/codes

[Update]  replication group  in README.md

---

README.md
codes/README.md

Update information on the paper replication group with some markdown format modification
- Updated codes/README.md with markdown format
- Updated README.md with markdown format
- Updated information on the paper replication group.
1. Remove paper replication details from README.md
2. Update replication goals and add selected replication papers(codes) information

[Update] information on the paper replication group with some markdown format modification

---

.github/pull_request_template.md

[Update] - update the formats of the PR template in pull_request_template.md
This pull request updates the formats of the PR template in pull_request_template.md. It might be more suitable for minisora's needs.
- Add title format and tag format.
- Update the description of each section.
- Delete unnecessary sections to make it concise.
- Closes #120 
According to the method provided by github official, it is impossible to directly set the title of PR. I make the title format one of the PR descriptions to ensure that the person submitting the PR understands …

[Update] - update the formats of the PR template in pull_request_template.md

---

README.md
README_EN.md

This PR adds three papers about Audio Related Resource to README an README_EN, which introduce some methods of joining audio and video generation.
-Added three resources to the Audio Related Resource section in the README and README_EN with links to papers and GitHub repositories.

Adding three articles to Audio Related Resource section

---

README.md
notes/README.md

[Update] Links about Sora and Presentation and Move details about Presentation information in readme.md to notes/readme.md 
1. Sora 夜谈之Video Diffusion 综述 添加跳转链接
2. Sora Tech Report添加两个中文翻译链接
3. Sora Tech Survey 添加中文翻译链接
4. 移动readme.md以往圆桌讨论详情到论文共读与圆桌讨论 notes/readme.md

[Update] Links about Sora and 圆桌讨论 and Move details about presentation information in readme.md to notes/readme.md 

---

README.md

This pull request adds Security and World Model Sections to README.md
[Add] Security and World Model Sections to  README.md

[Add] Security and World Model Sections to  README.md

---

README.md
notes/README.md

[Update] - add zhihu link to readme.md 
- add zhihu link to readme.md 
- Update zhihu link in notes/readme.md 

[Update] - add zhihu link to readme.md 

---

codes/README.md

Update remove redundency in title of codes/README.md

Update remove redundency in title of codes/README.md

---

notes/README.md

[Update] - change title level and add Mini Sora logo

[Update] - change title level and add Mini Sora logo

---

codes/README.md

[Remove] - 删除复现页面的微信二维码, 调整title

[Remove] - 删除复现页面的微信二维码, 调整title

---

codes/Text2Video.md

一键文本生成视频，非sora，技术栈 TTS + DALL·E + moviepy
文本转视频，通过输入文本，一键直接生成对应的视频。
1. 文本处理，分割文本，生成 prompt
2. 语音合成，将文本转换为语音 text to speech (TTS)，azure speech
3. 图片生成，将文本转成图片，openai DALL·E
4. 视频合成，将图片和语音合成视频，moviepy
详细代码 Github：https://github.com/HuZixia/Text2Video.git
Text2Vide 代码执行，不需要算力，需要 openai key 和 azure speech key 调用api。

Text2Vide.md TTS+DALLE+Moviepy

---

codes/Others/Text2Video.md
codes/README.md

1. Update the opensource project of `非Sora一键文本生成视频` from PR #154 in \codes\Others\Text2Video.md
2. Add 非Sora一键文本生成视频 information in codes/README.md

[Update] - 非Sora一键文本生成视频

---

README.md
README_EN.md

This pull request updates the README file with the latest research on diffusion models for visual computing, including the state-of-the-art paper and a comprehensive survey.
- Incorporated  [arxiv 23 Paper](http://arxiv.org/abs/2310.07204) "State of the Art on Diffusion Models for Visual Computing" and  [CSUR 24 Paper](https://dl.acm.org/doi/10.1145/3626235)" Diffusion Models: A Comprehensive Survey of Methods and Applications", along with the respective GitHub repo [Github](https://github.com/YangLing0818/Diffusion-Models-Papers-Survey-Taxonomy).
- **Please check if both …

[docs] add two survey papers to readme

---

README.md

[Move and Update 最近更新]
- Move and Update 最近更新
- Add two new survey papers
- Closes #159

[Update] - Move and Update 最近更新

---

README.md
README_EN.md

This pull request adds a comprehensive review of the latest advancements in text-to-video AI, specifically focusing on the OpenAI Sora, Stable Diffusion, and Lumiere models, to the README file.
- Added a section in the README with links to the [Generate Impressive Videos with Text Instructions: A Review of OpenAI Sora, Stable Diffusion, Lumiere and Comparable](https://www.techrxiv.org/users/684880/articles/718900-generate-impressive-videos-with-text-instructions-a-review-of-openai-sora-stable-diffusion-lumiere-and-comparable?commit=beb4b1d1e97ec6916a48a5a32b5fa5584ba096a8).
- Update hot news in Chinese and English readme. 
- Move the "Hot News" section in the English README to the front according to the chinese …

[docs] add sora techrxiv paper and update hot news

---

LICENSE

[Add] - Add apache2.0 license

---

README.md
README_EN.md

This pull request revises the README file by incorporating the missing first Sora paper into the hot news section and update the link to the Sora TechRxiv preprint by removing the unnecessary commit parameter. The first Sora paper is a pivotal video diffusion model designed for the task of efficient video generation.
- Added the first sora paper into the list of hot news. Removed the commit para in the link of paper.
- Please review the update content for accuracy and formatting.
- Closes #168 
- By updating the README with information on the …

[docs] Update the list of hot news and remove unnecessary para 

---

README.md

[Add] This pull request adds dataset tools to the README file.

[docs] add dataset tools

---

README.md

This pull request update Dataset to the README file.

[docs] Update Dataset

---

README.md
README_EN.md

Three open source datasets have been added to README & README_EN
- HD-VILA-100M
- HowTo100M
- YT-Temporal-180M

coderan add datasets - HD-VILA-100M, HowTo100M, YT-Temporal-180M

---

README.md
README_EN.md

This pull request adds references to three new survey papers on diffusion models to the README file. These papers cover the design fundamentals, efficiency, and t2I , t2V application of diffusion models in generative AI tasks.
- Added a section in the README with links to the survey papers on diffusion models.
- The addition of these survey papers will provide valuable insights and resources for users interested in diffusion models and generative AI.

[docs] add three diff survey papers

---

README.md
README_EN.md

This pull request adds information about the **GenTron** paper to the README file. GenTron is video diffusion model for.

add [CVPR24] GenTron

---

README.md
README_EN.md

Update README.md
fixs readme.md table format

[docs] Update fixs readme.md table format

---

README.md

This pull request adds PROJECT SHIELDS to README.md

[Update] - adds PROJECT SHIELDS to README.md 

---

README.md
README_EN.md

[Add] -add PROJECT SHIELDS for Chinese and English README

[Add] -add PROJECT SHIELDS for Chinese and English README

---

README_EN.md

This pull request updates README_EN.md with PROJECT SHIELDS
- Added an empty line before footer PROJECT SHIELDS

[Update] - README_EN.md with PROJECT SHIELDS

---

docs/README.md
docs/README_EN.md

This PR is for fixing the Issue #150 which wanted to add a file description in docs/README.md
- Added a file description in docs/README.md and the index to CONTRIBUTING.md
- Closes #150

[Update] - fix Issue #150 (file description in docs/README.md)

---

docs/README.md
docs/README_EN.md

This pull request update docs/README.md fix the file link and add the project logo in readme.md
- #182 
- #150

[Update] Update docs/README.md fix the file link

---

README.md
README_EN.md

[Add] - add a [Add] - add a Consistency paper related to dependency

[Add] - add a [Add] - add a Consistency paper related to dependency

---

README.md
README_CN.md
codes/README.md
codes/README_CN.md
codes/pipeline/README.md
codes/pipeline/README_EN.md
docs/README.md
docs/README_CN.md
notes/README.md

This pull request changes main pages as English version in several folders

[Update] - change main page as English version

---

README.md

English readme is inconsistent with Chinese and I updated

[Update] - synchronize with readme.md

---

README.md

This pull request turns the "base" in the README.md into the same "baseline" as in the README_CN.md

[docs] Fixed a minor issue with the description in README.md 

---

codes/README_CN.md

[docs] update readme for opendit
This pull request updates information about the OpenDiT project to the README file.

[docs] update readme for opendit

---

README.md
README_CN.md

Update ReadMe file for Base Video Generation Models
This pull request adds information about the video diffusion related papers and  projects to the README file. 
-Stable Video Diffusion is for video generation
-Text2Video-Zero is for zero-shot video generation
-VideoCrafter2 is for high quality video generation
- Added a section in the README with links to the video diffusion related papers, GitHub repository, and project website.
- Closes #issue-number (if there's an associated …

Update ReadMe file for Base Video Generation Models

---

README.md
README_CN.md

add VisionLLaMA

---

README.md
README_CN.md

[Update] - update readme.md and readme_cn.md about prompt engineering
removed duplicates and bolded some of the literature titles
- removed duplicates and bolded some of the literature titles

[docs]: update readme.md and readme_cn.md about prompt engineering

---

README.md
README_CN.md

[Add] - Patches Project
Interactive Video Stylization Using Few-Shot Patch-Based Training.
Zoom-VQA: Patches, Frames and Clips Integration for Video Quality Assessment.
FlexiViT: One Model for All Patch Sizes (Multi-scale patches)
ADD: Interactive Video Stylization Using Few-Shot Patch-Based Training.
ADD: Zoom-VQA: Patches, Frames and Clips Integration for Video Quality Assessment.
ADD: FlexiViT: One Model for All Patch Sizes (Multi-scale patches)

Add Patches Project

---

README.md
README_CN.md

This pull request adds information about the NaturalSpeech 2/UniAudio paper to the README file. NaturalSpeech 2 is tts system with latent diffusion models .
- Added a section in the README with links to the NaturalSpeech 2 paper, GitHub repository.
- Added a section in the README with links to the UniAudio paper, GitHub repository.
- Checked both the Chinese and English READMEs have been updated at the same time
- Closes …

Add Audio Related Resource Consistency

---

codes/README.md
docs/README.md
docs/README_CN.md

update README.md and Readme_CN.md in codes and docs
Modify the links to Readme.md and Readme_CN.md
- Why is the README.md in the codes directory also Chinese?
-

[Bugs] about README.md and Readme_CN.md in codes and docs

---

README.md
README_CN.md

[Update] - replace [Paper] to [**Paper**]
modify format
[Update] - replace [Paper] to [**Paper**]

Modified format all

---

README.md

remove semicolon as it is not proper

remove semicolon

---

docs/README_CN.md

update docs/README_CN.md that modify the index path in the file to be correct

[Update] docs/README_CN.md file link

---

README.md
README_CN.md

[Add] - add MM-DiT

---

.github/pull_request_template.md
README.md
README_CN.md
docs/CONTRIBUTING.md
docs/CONTRIBUTING_EN.md

[docs]: modify docs according to #217

---

README.md
README_CN.md

This PR adds five papers about Security to README and README_EN, introducing some ethics and security methods.
-Added five resources to the Security section in README and README_EN with links to papers and GitHub.

Adding five papers to Security

---

README.md
README_CN.md
docs/HOT_NEWS_BASELINES_GUIDES.MD
docs/HOT_NEWS_BASELINES_GUIDES_CN.MD

- [add guides md for Hot News and Baseline Sections](https://github.com/mini-sora/minisora/commit/1666b1e086f7b1ee8be0539ba9ec257dbe4d1c2f)
- [add MiniSora-DiT and reorganize Reproduction Group of MiniSora Community](https://github.com/mini-sora/minisora/commit/ffb4e8148d6cfbb23e82c4d6eb729f7db89acc7b)

[Add+Update] add MiniSora-DiT and reorganize Reproduction Group of MiniSora Community

---

README.md

This pull request adds two downloadable datasets to README file.

[docs]: add two downloadable datasets to README.md

---

README_CN.md

This pull request add two downloadable datasets to README_CN file.

[docs]: add two downloadable datasets to README_CN.md

---

README.md

[Update] - update minisora-DiT link

---

README.md

Please read [CONTRIBUTING](../docs/CONTRIBUTING_EN.md) manual before submitting your PR.
- The addition of XXX to our README will provide …

[Doc] Update XTuner Link

---

README.md
README_CN.md

1.Undownloadable datasets were deleted.
2.Added high-quality datasets, _e.g._ InternVid-10M, CelevV-Text, HD-VG-130M.
3.The number and resolution of dataset clips are marked.
4.The datasets are sorted by year.

coderan update 10 datasets

---

README_CN.md

[Update] README_CN.md with xtuner link

[Update] README_CN.md with xtuner link

---

README.md
README_CN.md

Please read [CONTRIBUTING](../docs/CONTRIBUTING_EN.md) manual before submitting your PR.
- This pull request adds information about the Open-Sora paper and project to the README file. Open-Sora is an open-source project that provides a complete Sora reproduction architecture solution.
- Closes #235 
- The addition of Open-Sora to our README will …

[Add] hpc Open-Sora project to repo's resources

---

codes/README.md
codes/README_CN.md

[Update] - updae codes/README.md with respect #234
Close #234

[Update] - updae codes/README.md with respect #234

---

notes/README.md
notes/README_CN.md

Please read [CONTRIBUTING](../docs/CONTRIBUTING_EN.md) manual before submitting your PR.
- Closes #244 
- The addition of XXX to our README will provide valuable resources for users interested in …

Solve the Issue #244

---

.github/CONTRIBUTING.md
.github/CONTRIBUTING_zh-CN.md
.github/pull_request_template.md
README.md
README_zh-CN.md
codes/README.md
codes/README_zh-CN.md
codes/pipeline/README.md
codes/pipeline/README_zh-CN.md
docs/HOT_NEWS_BASELINES_GUIDES.md
docs/HOT_NEWS_BASELINES_GUIDES_zh-CN.md
docs/README.md
docs/README_zh-CN.md
notes/README.md
notes/README_zh-CN.md

Please read [CONTRIBUTING](../docs/CONTRIBUTING_EN.md) manual before submitting your PR.
- The addition of XXX to our README will provide …

[docs]: reformat docs

---

README.md
README_zh-CN.md

[Add] BLIP and BLIP-2 to **Patches Project**
[Add]  LAVIS to **Resource**
This pull request adds information about the BLIP and BLIP-2 paper and LAVIS project to the README file.

[Add] BLIP and BLIP-2 to Patches Project AND [Add]  LAVIS to Resource

---

README.md
README_zh-CN.md
notes/README.md
notes/README_zh-CN.md

Add new paper discussion && Fix some typo
This pull request adds information about the DistriFusion paper discussion
- Added a section in the README with links to the DistriFusion wechat link

Add new paper discussion && Fix some typo

---

README.md

This pull request adds datasets the README file.

[docs] add datasets to README file

---

README_zh-CN.md

This pull request adds datasets to the README_zh-CN file.

[docs] add datasets to README_zh-CN file

---

README.md
README_zh-CN.md

[Update] - README，add papers in the "Patchifying Methods" module
This pull request adds information about the "Patchifying Methods" paper to the README file. 
- Added some papers in "Patchifying Methods" in the README 
- Delete two papers for they were not relevant.
- The addition of "Patchifying Methods" to our README will provide valuable resources for users interested in efficient video generation.

Update README，add "Patchifying Methods"

---

README.md
README_zh-CN.md

[Docs] Add video compression

---

README.md

This pull request update the datasets on README file.

[docs] Update datasets on README.md

---

README_zh-CN.md

This pull request adds datasets to the README_zh-CN file.

[docs] add datasets to README_zh-CN.md

---

README.md
README_zh-CN.md

This PR adds several papers about Security to README and README_EN, introducing some security methods.
-Added several resources to the Security section in README and README_EN with links to papers and GitHub.

Adding articles about security

---

README.md
README_zh-CN.md

[Update] - updata README.md & README_zh-CN.md

[Update] - updata README.md & README_zh-CN.md

---

README.md
README_zh-CN.md

This pull request adds information about the Audio Related Resource paper and project to the README file, remove the extra commas for 'Layered Neural Atlases for Consistent Video Editing' in the en/zh ver.
- Added a section in the README with links to the Audio Related Resource paper, GitHub repository, and project website.
- Remove the extra commas for 'Layered Neural Atlases for Consistent Video Editing' in the en/zh ver.
- **Please check if …

[docs] update README.md & README_zh-CN.md about audio papers

---

README.md
README_zh-CN.md

Opitimization of contents
- Move OpenDiT into Useful Sources
- Change title “Minisora Community WeChat Group”
- add dit paper into baselines and remove LVDM
- add latte paper into baselines

[Update] Opitimization of contents (DiT, Latte, OpenDiT, and so on)

---

README.md
README_zh-CN.md

[Update] - add project to ViT paper

[Update] - add project to ViT paper

---

README.md
README_zh-CN.md

[Update] - add project and github link for paper FlowZero #254
- Closes #254

[Update] - add project and github link for paper FlowZero #254

---

README.md
README_zh-CN.md

This pull request fix link about the "Diffusion Models in Vision: A Survey" paper to the README file.
Updated the README to point to the accurate paper.
Ensured that the links are functional and the information is up-to-date.
Please review the updated content for accuracy and formatting.
Check that the links provided are correct and lead to the intended resources.
Please check if both the Chinese and English READMEs have been updated simultaneously.
Closes #277

[Correct] the link of "Diffusion Models in Vision: A Survey" 

---

README.md
README_zh-CN.md

[add MemoryBank to long-context bank paper](https://github.com/mini-sora/minisora/commit/6a0e59af124d9ee0e23606587b493ad87932c2f7)

[Update] - add MemoryBank to long-context bank paper

---

README.md
README_zh-CN.md

add dataset VidProM

---

README.md
README_zh-CN.md

[Update] - update Paper Reading Program

[Update] - update Paper Reading Program

---

README.md

update sd3 link

---

README_zh-CN.md

[Update] - update sd3 link

---

README.md

[Add] - more prompt engineering papers
add ten papers about prompt engineering
- The addition of XXX to our README will provide valuable resources for users interested in efficient video …

[docs]: more prompt engineering papers

---

README_zh-CN.md

[Update] - change prompt_engineering part in readme_cn
change prompt_engineering part in readme_cn
- The addition of XXX to our README will provide valuable resources for users interested in …

[docs]: change prompt_engineering part in readme_cn

---

README.md
README_zh-CN.md

[Update] - updata Mamba papers in README.md & README_zh-CN.md

[Update] - updata Mamba papers in README.md & README_zh-CN.md

---

README.md

Update table contents in README.md

Update table contents in README.md

---

README.md
README_zh-CN.md

updata README.md & README_zh-CN.md

[Updata] - updata README.md & README_zh-CN.md

---

README.md
README_zh-CN.md
docs/README_zh-CN.md
docs/survey_README.md
docs/survey_README_zh-CN.md
notes/README.md
notes/README_zh-CN.md
notes/SD3_zh-CN.md

Update round-table discussion

---

README.md
README_zh-CN.md

This pull request adds two links about the "Awesome-Long-Context" project to the README file. 
- Added "Awesome-Long-Context" in the README with two links to the GitHub repository.
- The addition of "Awesome-Long-Context" to our README will provide valuable resources for users interested in long-context.

[ADD] - "Awesome-Long-Context" in README && README_CN

---

README.md
README_zh-CN.md

[Add] -  videoMamba paper and github
This pull request introduces the integration of VideoMamba: State Space Model for Efficient Video Understanding into the README file. VideoMamba is an innovative video diffusion model designed to address the challenges of local redundancy and global dependencies in the domain of video understanding.
- A new section has been added to the README, which includes links to the VideoMamba paper, its GitHub repository, and the project's website.
- Check that the links provided are correct and …

[docs] Add videoMamba paper and github

---

README.md
README_zh-CN.md

This pull request adds information about the VideoPoet paper and project to the README file. VideoPoet is a large language model designed for zero-shot video generation, capable of creating videos from textual descriptions without prior training on video data for specific tasks.
- Added a section in the README with links to the VideoPoet paper, Blog, and project website.
- **Please check if both the Chinese and English READMEs have been …

[docs] update the info of videoPoet, and add it to audio resources

---

README.md
README_zh-CN.md

This pull request adds information about the AudioLDM  paper and project to the README file. 
- Added a section in the README with links to the AudioLDM  paper, GitHub repository, and project website.
- Closes #299 
- AudioLDM is the first TTA system that enables various text-guided audio manipulations (e.g., style transfer) in a zero-shot fashion.

[docs]Add audioldm

---

README.md
README_zh-CN.md

[Add] - Improved DDPM to Diffusion model
This pull request adds information about the improved DDPM paper and github link to the README file. It's an important foundation work
- Added a section in the README with links to the improved DDPM paper, GitHub repository.
- Closes #297
- The addition of improved DDPM to our README will provide valuable …

[Add] - Improved DDPM to Diffusion model

---

README.md
README_zh-CN.md

297 add improved ddpm to diffusion model

297 add improved ddpm to diffusion model

---

README.md
README_zh-CN.md

[Update] - Add Sora Survey Plan and citations

[Update] - Add Sora Survey Plan and citations

---

README.md

This pull request adds PIXART to the README file.

[docs] add PIXART to README file

---

README_zh-CN.md

This pull request adds PIXART to the README_zh-CN file.

[docs] add PIXART to README_zh-CN file

---

README.md

This pull request update PIXART to the README file.

[docs] Update PIXART on README.md

---

README_zh-CN.md

This pull request updata PIXART to the README_zh-CN file.

[docs] Update PIXART on README_zh-CN.md

---

README.md
README_zh-CN.md

This pull request adds information about the Audio Related Resource paper and project to the README file.
- Added a section in the README with links to the Audio Related Resource paper, GitHub repository, and project website.
- Closes #323 
- The update is necessary to provide accurate and accessible resources for users interested in Audio Related …

[docs] update README.md & README_zh-CN.md about audio papers 

---

README.md

Update README.md about MiniSora-DiT

Update README.md about MiniSora-DiT

---

README.md
README_zh-CN.md

ELLA makee use of the LLM enable diffusion models understand long prompts.
README.md and README_zh-CN.md is updated.

[Add] Add ELLA to Prompt Engineering by John Ge.

---

README.md
README_zh-CN.md

Add LAVIE Paper and GitHub link

Add LAVIE Paper and GitHub

---

README.md
README_zh-CN.md

Add ICCV2023 paper PYoCo and another paper VideoFusion

Add ICCV2023 paper PYoCo and another paper VideoFusion

---

README.md
README_zh-CN.md

[Add] - add papers about recaption
add papers about recaption

[docs]: add papers about recaption

---

README.md
README_zh-CN.md

[Update] update the paper information in README
-  #fixes #331

[docs] update paper information in README.md & README_zh-CN.md

---

README.md
README_zh-CN.md

This PR adds three papers about Security to README and README_EN, introducing some alignment methods.
-Added three resources to the Security section in README and README_EN with links to papers and GitHub.

Adding three articles to Security Section

---

README.md
README_zh-CN.md

Add Pixabay100 dataset
- Closes #334

Add Pixabay100 dataset

---

README.md
README_zh-CN.md

Update Dr. Yang Song's paper on consistency generative models

[Update] - Update Dr. Yang Song's paper on consistency generative models

---

README.md
README_zh-CN.md

[Correct] - change section name of recaption
change section name of recaption

[docs]: change section name of recaption

---

README.md

Update README.md with added section `Diffusion UNet` and one paper this section
Add paper “Taming Transformers for High-Resolution Image Synthesis”

Update README.md with added section `Diffusion UNet` and one paper

---

README.md
README_zh-CN.md

Add paper Taming Transformers for High-Resolution Image Synthesis

Add paper Taming Transformers for High-Resolution Image Synthesis

---

README.md
README_zh-CN.md

Update the parts of `Dataset`,`Efficient Training` and `Efficient Inference`
- closes #341 #346

Update the parts of `Dataset`,`Efficient Training` and `Efficient Inference`

---

README.md
README_zh-CN.md

[Update] - add lite-sora for useful resource
This pull request adds information about the project lite-sora to the README file. XXX is xxx video diffusion model for xxx task.
- Added a section in the README with links to the lite-sora GitHub repository
- Closes #333 
- The addition of lite-sora to our README will provide valuable resources for users …

[Update] - add lite-sora for useful resource

---

README.md
README_zh-CN.md

Reverts mini-sora/minisora#348

Revert "[Update] - add lite-sora for useful resource"

---

README.md
README_zh-CN.md

Reverts mini-sora/minisora#349

Revert "Revert "[Update] - add lite-sora for useful resource""

---

README.md
README_zh-CN.md

333 add lite sora to useful resources

333 add lite sora to useful resources

---

README.md
README_zh-CN.md

Adding new paper about ZigMa: a DiT-style mamba-based backbone for diffusion models.

---

README.md
README_zh-CN.md

Standardize the Labels of arXiv Papers
- README.md and README_zh-CN.md
- #291

Update Standardize the Labels of arXiv Papers

---

README.md
README_zh-CN.md

add new recaption papers
[Add] - add new recaption papers
add new recaption papers

[docs]: add new recaption papers

---

README.md
README_zh-CN.md

Update section of `Efficient Training`
Preview at: https://github.com/BestAnHongjun/minisora

Update Efficient Training

---

README.md

add mira dataset Update README.md

---

README.md
README_zh-CN.md

add mira github

---

README.md
README_zh-CN.md

[Update] - update recaption papers
update recaption papers

[docs]: update recaption papers

---

README.md
README_zh-CN.md

This pull request adds information about the diffusion model paper and project to the README file.
- Added a section in the README with links to the diffusion model paper, GitHub repository, and project website.
- Closes #364 
- The update is necessary to provide accurate and accessible resources for users interested in diffusion model.

[docs] update README.md & README_zh-CN.md about diffusion model papers

---

README.md
README_zh-CN.md

add PipeFusion
This pull request adds information about the xx paper and PipeFusion project to the README file. PipeFusion is a parallel inference approach for the diffusion model. 
- The addition …

add PipeFusion Paper

---

README.md
README_zh-CN.md

[Update] - Update mamba paper
This pull request adds information about the Hybrid Mamba-Transformer Vision Backbone paper to the README file.
- Added a section in the README with links to the hybrid model paper, GitHub repository, and project website.
- The addition of XXX to our README will …

[docs]: update mamba paper

---

README.md
README_zh-CN.md

This pull request adds information about the diffusion transformer model paper and project to the README file.
- Added a section in the README with links to the diffusion transformer model paper, GitHub repository, and project website.
- Closes #370  
- The update is necessary to provide accurate and accessible resources for users interested in …

[docs] update README.md & README_zh-CN.md about diffusion transformer model papers 

---

README.md
README_zh-CN.md

Add IDForge dataset to the dataset section.

Add IDForge Dataset

---

README.md
README_zh-CN.md

This pull request adds information about the video generation & audio-related papers and projects to the README file.
- Added a section in the README with links to the diffusion transformer model paper, GitHub repository, and project website.
- Closes #372 
- The update is necessary to provide accurate and accessible resources for users interested in …

[docs] update README.md & README_zh-CN.md about video generation & audio-related papers and fix bugs 

---

README.md
README_zh-CN.md

This pull request adds information about Sora and GitHub Trending information to the README file.
- Added a section in the README with the link to Sora.
- Added a section in the README with the GitHub Trending information.
- Closes #374  
- The update is necessary to provide accurate and accessible resources for users interested in Sora.

[docs] add news about Sora and GitHub Trending information
